### ISSUE TITLE
configuration error

### ISSUE THREAD

**Issue by danielgontz** [whatbirdisthat/cyberdolphin#3]
Hello, I still get this error in my console:

`[ERROR] An error occurred while retrieving information for the '🐬 OpenAI Compatible' node.
Traceback (most recent call last):
  File "D:\_AI\ComfyUI_windows_portable\ComfyUI\server.py", line 418, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "D:\_AI\ComfyUI_windows_portable\ComfyUI\server.py", line 396, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\cyberdolphin\cyberdolphin_openai_compatible.py", line 14, in INPUT_TYPES
    default_model = all_settings['openai_compatible']['default']['model']
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'default'`

Please advise

**Comment by whatbirdisthat** [comment]
thanks @danielgontz here's the fix:
change the entry for `local_vllm_openai_api` to `default` in settings.yaml (line 10 in settings.yaml.example)

I pushed up a fix to `settings.yaml.example` too.
